"""Reference data for the staff operations checklist module.

Defines the recurring daily checklists, the food temperature record templates,
and the lookup tables for staff names and issue categories. Kept as a Python
module so the operations team can hand-edit task lists without touching the DB.
"""

from __future__ import annotations


CHECKLISTS: dict[str, dict] = {
    "take_order": {
        "title": "Cashier",
        "short": "Cashier",
        "accent": "#ff6a13",
        "opening": [
            "Open till & check cash balance ($350)",
            "Uniform check (hat, shirt, apron)",
            "Counter area ready for service, clean surrounding counter area",
            "Check the POS system - tills and EFTPOS all working",
            "Prepare vegetables & garnish for pho and bun bo hue",
            "Label beverages and label price and name for pastry",
            "Record temperature of fried pastry food (Pastry Temperature Record)",
            "Arrange the line-up for customers to take order",
            "Complete checklists (Food Temperature Records)",
            "Receive bread & pastry invoices from supplier",
        ],
        "closing": [
            "Take orders & resolve service issues (during shift)",
            "Clean the counter area",
            "Clean display glass cabinets",
            "Clean Cold Unit 2 Soft Drink Fridge",
            "Clean Cold Unit 3 Rice Paper Roll Fridge",
            "Refill drinking water",
            "Refill spoons, forks, chopsticks & sauces",
            "Buy bean sprouts, mint & veg for pho and bun bo hue for tomorrow",
            "Check income & till balance before closing",
            "Clean front floor",
            "Clean air fryer",
            "Check banh mi packaging bag order with Huu Anh",
            "Refill receipt roll",
            "Refill carry bags, paper bags & cup holders for takeaway",
            "Collect invoices & send to office every Friday (give to Van Anh)",
        ],
    },
    "banh_mi": {
        "title": "Banh Mi",
        "short": "Banh Mi",
        "accent": "#ffb436",
        "opening": [
            "Set up & display banh mi fridge bar (banh mi, red pork, cha lua, cha gan, ngo, pickles, sliced chilli, cucumber)",
            "Check & test quality of each item (report to Manager if food not good to sell)",
            "Cut bread, spread pate & butter",
            "Display plain bread in the basket",
            "Set up roast pork station",
            "Chop roast pork & chicken",
            "Pre-make roast pork banh mi (all prep done by 8:00 AM)",
            "Change gloves for vegetarian orders",
            "Order coriander, cucumber & radish from supermarket",
            "Complete Banh Mi Food Temperature Record",
            "Customer order service (prepare banh mi per requests)",
        ],
        "closing": [
            "Prepare next-day veg: coriander, cucumber, soy sauce follow prep timetable",
            "Prepare food in the tray for tomorrow setup (coriander, pickle, cucumber, sauce: soy, gravy, mayo)",
            "Defrost pate (move from freezer to fridge for tomorrow)",
            "Clean up banh mi station",
            "Sanitise the roast pork table & chopping board",
            "Clean Cold Unit 4 Banh Mi Fridge (end of day)",
            "Wash dishes, final dish check at 4:30 PM",
        ],
    },
    "chef": {
        "title": "Chef / Kitchen",
        "short": "Chef",
        "accent": "#eb5130",
        "opening": [
            "Turn on lights and ventilation/exhaust fan",
            "Turn on gas & all kitchen equipment",
            "Cook rice",
            "Make savoury sticky rice",
            "Grill the pork chop",
            "Marinate chicken & pork followed food preparation timetable",
            "Pho soup station set up",
            "Set up rice noodle (pho noodle, BBH noodle, dry noodles)",
            "Set up chef fridge bar station (coriander, mint, tomato, cucumber, salad onion, spring onion, raw beef, cooked beef, beef ball, pork, etc.)",
            "Fry fried pastry items (fried spring roll, samosa, banana, etc.)",
            "Fry eggs for service",
            "Packaging items filled",
            "Customer order service",
            "Complete Chef Section Food Temperature Record",
        ],
        "closing": [
            "Marinate chicken & pork for next day followed food preparation timetable",
            "Prepare fish sauce and soy sauce for tomorrow",
            "Prep & store next-day food properly",
            "Clean kitchen areas & equipment",
            "Spray & wash kitchen floor",
            "Clean back floor",
            "Clean grilled machine",
            "Clean oven",
            "Clean stove",
            "Clean gas burners",
            "Clean deep fryer",
            "Clean Cold Unit 6 Soup & Rice Fridge",
            "Clean Cold Unit 7 Noodle & Soup Bar",
            "Clean Cold Unit 8 Food Prep Fridge",
            "Clean cold food fridge",
            "Clean the display fridge bar",
            "All kitchen equipment turned OFF",
            "Gas turned OFF",
            "Water turned OFF",
            "Kitchen lights OFF",
            "Door locked",
        ],
    },
    "grill_beef": {
        "title": "Kitchen Hand",
        "short": "K.Hand",
        "accent": "#28724d",
        "opening": [
            "Roast pork (10-15/day, 15-20 weekends)",
            "Grill chicken (2 trays/day, 3-4 weekends)",
            "Stir-fry beef / pork / tofu",
            "Slice beef ~5 kg for pho & banh mi",
            "Slice pork & char siu meat",
            "Beef soup Tue/Thu/Sat - Char siu Mon/Wed/Fri",
        ],
        "closing": [
            "Check & refill seasonings",
            "Prepare food for next day when time allows",
            "Clean the preparation area",
            "Empty rubbish bins",
            "Wash dishes",
            "Scrub & clean back floor",
            "Clean Freezer 1",
            "Clean Freezer 2",
        ],
    },
    "serve_order": {
        "title": "Serve Order / Drinks",
        "short": "Drinks",
        "accent": "#006f74",
        "opening": [
            "Prepare black iced coffee base (at least 2 jars)",
            "Prepare watermelon / tropical / sugarcane juice",
            "Prepare smoothie base mix",
            "Wash sugarcane",
            "Prepare fresh rice paper rolls for the day",
            "Make at least 1 tropical juice, 1 jar watermelon juice, 1 jar sugarcane juice, 4 jars black iced coffee",
            "Check coffee, condensed milk & fruit stock",
        ],
        "closing": [
            "Peel & prepare fruit for juice (next day): orange, apple, watermelon, etc.",
            "Refill fruit containers, lids clean & covered",
            "Set up & check quality, clean fruit juice in the fridge",
            "Check enough coffee / condensed milk",
            "Clean fruit juicer",
            "Clean sugarcane juicer",
            "Change fruit display (Mon, Wed, Fri, Sun)",
            "Wash all drink containers",
            "Check & refill cups, lids, straws",
            "Wash banh mi trays",
            "Bag returned pastry, bring to counter",
            "Clean microwave",
            "Clean pastry tray",
            "Clean Cold Unit 1 Fruit Juice Fridge",
            "Clean Cold Unit 5 Coffee Fridge",
            "Clean front floor",
            "Work area tidy, lights off",
        ],
    },
}


TEMPERATURE_RECORDS: dict[str, dict] = {
    "banh_mi": {
        "title": "Banh Mi Food Temperature Record",
        "short": "Banh Mi",
        "accent": "#ffb436",
        "foods": [
            "Cooked Pork Ham (Cha Lua)",
            "Cooked Pork Meat (Thit Nguoi)",
            "Cooked Pork Jelly (Gio Thu)",
            "Roasted Pork",
            "Roasted Chicken",
            "Stir-Fry Beef",
            "Stir-Fry Pork",
            "Stir-Fry Tofu",
            "Pate",
            "Butter",
            "Pickled",
            "Coriander",
            "Cucumber",
            "Carrot Pickled",
        ],
    },
    "chef": {
        "title": "Chef / Noodle Soup & Rice Temperature Record",
        "short": "Chef",
        "accent": "#eb5130",
        "foods": [
            "Cooked Beef",
            "Raw Beef",
            "Cooked Beef Ball",
            "Cooked Pork",
            "Cooked Pork Ham",
            "Pho Noodle",
            "Rice Vermicelli Bun",
            "Pork Chop",
            "Egg",
            "Pickled",
            "Cucumber",
            "Lettuce",
            "Tomato",
        ],
    },
    "pastry": {
        "title": "Pastry / Hot Food Temperature Record",
        "short": "Pastry",
        "accent": "#d94c79",
        "foods": [
            "Sesame Ball",
            "Sesame Bread",
            "Fried Pork Dumpling",
            "Steam Bun",
            "Sweet Donuts",
            "Chinese Donut",
            "Fried Banana",
            "Pork Pastry",
            "Bird Nest Cake",
            "Curry Puff",
            "Spring Roll",
            "Banana Banh Tet",
            "Beef Samosa",
            "Banh Bao (Dumpling)",
        ],
    },
}


STAFF_ROSTER: tuple[str, ...] = (
    "DANG, THI LAN UY",
    "DOAN, THI NI",
    "NGUYEN, PHU TAN",
    "HUYNH, ANH TRI",
    "Thang Nguyen",
    "MA, THANH PHUNG",
    "NGUYEN, THI NHAI",
    "NGUYEN, VAN PHI LONG",
    "DO, NGUYEN",
    "NGUYEN, THI NGOC PHUC",
    "Ho Quynh",
    "NGUYEN, HANG SANG",
    "VU, TRAN DO CAO",
)


MANAGERS: tuple[str, ...] = ("MA, THANH PHUNG", "Khoi")


ISSUE_CATEGORIES: dict[str, dict[str, str]] = {
    "conflict": {"label": "Staff Conflict / Bullying", "accent": "#eb5130"},
    "equipment": {"label": "Equipment Issue", "accent": "#ff6a13"},
    "supplies": {"label": "Supply / Stock Request", "accent": "#006f74"},
    "hr": {"label": "HR / Salary Issue", "accent": "#d94c79"},
    "timesheet": {"label": "Missed Clock-in / Clock-out", "accent": "#28724d"},
    "suggestion": {"label": "Idea / Suggestion", "accent": "#ffb436"},
    "customer": {"label": "Customer Complaint", "accent": "#eb5130"},
    "food_safety": {"label": "Food Safety Concern", "accent": "#c62828"},
    "maintenance": {"label": "Maintenance / Facility", "accent": "#558b2f"},
    "other": {"label": "Other", "accent": "#6c584f"},
}


REACTION_TYPES = ("opening", "closing")
SECTION_DEADLINES = {"opening": (10, 30), "closing": (18, 30)}
PHOTOS_REQUIRED = 4
ALLOWED_PHOTO_EXTENSIONS = {"jpg", "jpeg", "png", "gif", "webp", "heic", "heif"}
